# The title is the title of your Add-On
title: N-Gram Graphs
# The description will be shown above the form when activating the Add-On
description: This add-on will create word frequency graphs over time. 
# Type should always be object
instructions: ''
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the current search query
  - query
  # By the currently selected documents
  - selected
# Properties are the fields for your form
properties:
  # the key is the name of the variable that will be returned to your code
  string1:
    # the title is what will be shown as the form label
    title: Word 1
    # a string is text
    type: string
  string2:
    # the title is what will be shown as the form label
    title: Word 2
    # a string is text
    type: string
categories:
  - statistical

